"""initial normalized intelligence schema"""

from alembic import op
import sqlalchemy as sa

revision = "0c84da38558c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("source_id", sa.String(length=250), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("cron", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "radar_horizons",
        sa.Column("id", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("years", sa.String(length=30), nullable=False),
        sa.Column("min_maturity", sa.Float(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("score_rules", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("roles", sa.Column("name", sa.String(length=20), nullable=False), sa.PrimaryKeyConstraint("name"))
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "technology_domains",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "technologies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("horizon", sa.String(length=2), nullable=False),
        sa.Column("maturity", sa.Float(), nullable=False),
        sa.Column("strategic_relevance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("analyst_notes", sa.Text(), nullable=False),
        sa.Column("last_reviewed", sa.DateTime(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain"],
            ["technology_domains.name"],
        ),
        sa.ForeignKeyConstraint(
            ["horizon"],
            ["radar_horizons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("technologies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_technologies_domain"), ["domain"], unique=False)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role"],
            ["roles.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "ai_analyses",
        sa.Column("technology_id", sa.String(length=36), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=30), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("token_usage", sa.JSON(), nullable=False),
        sa.Column("approval_status", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_analyses_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("before", sa.JSON(), nullable=False),
        sa.Column("after", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)

    op.create_table(
        "detected_signals",
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("rule", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    with op.batch_alter_table("detected_signals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_detected_signals_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("website", sa.Text(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("domains", sa.JSON(), nullable=False),
        sa.Column("technology_id", sa.String(length=36), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("analyst_notes", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("normalized_name"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_organizations_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "pipeline_runs",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("technology_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("parent_run_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "radar_history",
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.Column("old_horizon", sa.String(length=2), nullable=False),
        sa.Column("new_horizon", sa.String(length=2), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("radar_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_radar_history_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "technology_keywords",
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.Column("keyword", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("technology_id", "keyword"),
    )
    with op.batch_alter_table("technology_keywords", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_technology_keywords_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "technology_scores",
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("technology_scores", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_technology_scores_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "briefings",
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("technology_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "institutions",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("openalex_id", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id"),
        sa.UniqueConstraint("openalex_id"),
    )
    op.create_table(
        "pipeline_steps",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("processed", sa.Integer(), nullable=False),
        sa.Column("inserted", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pipeline_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pipeline_steps_run_id"), ["run_id"], unique=False)

    op.create_table(
        "staged_evidence",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("staged_evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_staged_evidence_run_id"), ["run_id"], unique=False)

    op.create_table(
        "startups",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("development_stage", sa.String(length=80), nullable=False),
        sa.Column("public_funding_signal", sa.Text(), nullable=False),
        sa.Column("research_partners", sa.JSON(), nullable=False),
        sa.Column("patents_found", sa.JSON(), nullable=False),
        sa.Column("source_urls", sa.JSON(), nullable=False),
        sa.Column("latest_signal_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id"),
    )
    op.create_table(
        "technology_assessments",
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("horizon", sa.String(length=2), nullable=False),
        sa.Column("maturity", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["ai_analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["horizon"],
            ["radar_horizons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("technology_assessments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_technology_assessments_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "technology_evidence",
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=300), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("doi", sa.String(length=250), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
        sa.UniqueConstraint("source_id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("technology_evidence", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_technology_date", ["technology_id", "published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_technology_evidence_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_technology_evidence_is_demo"), ["is_demo"], unique=False)
        batch_op.create_index(batch_op.f("ix_technology_evidence_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_technology_evidence_published_at"), ["published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_technology_evidence_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_technology_evidence_source_type"), ["source_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_technology_evidence_technology_id"), ["technology_id"], unique=False)

    op.create_table(
        "web_sources",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_checked", sa.DateTime(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "evidence_technologies",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("technology_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["technology_evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("evidence_id", "technology_id"),
    )
    op.create_table(
        "news_signals",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("domain", sa.String(length=250), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["technology_evidence.id"],
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_table(
        "papers",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("citation_count", sa.Integer(), nullable=False),
        sa.Column("journal", sa.Text(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("semantic_scholar_id", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["technology_evidence.id"],
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
        sa.UniqueConstraint("semantic_scholar_id"),
    )
    op.create_table(
        "patents",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("applicant", sa.Text(), nullable=False),
        sa.Column("inventor", sa.Text(), nullable=False),
        sa.Column("classifications", sa.JSON(), nullable=False),
        sa.Column("family", sa.Text(), nullable=False),
        sa.Column("legal_status", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["technology_evidence.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evidence_id"),
    )
    op.create_table(
        "paper_authors",
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.evidence_id"],
        ),
        sa.PrimaryKeyConstraint("paper_id", "author_id"),
    )
    op.create_table(
        "paper_institutions",
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.organization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.evidence_id"],
        ),
        sa.PrimaryKeyConstraint("paper_id", "institution_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_institutions")
    op.drop_table("paper_authors")
    op.drop_table("patents")
    op.drop_table("papers")
    op.drop_table("news_signals")
    op.drop_table("evidence_technologies")
    op.drop_table("web_sources")
    with op.batch_alter_table("technology_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technology_evidence_technology_id"))
        batch_op.drop_index(batch_op.f("ix_technology_evidence_source_type"))
        batch_op.drop_index(batch_op.f("ix_technology_evidence_run_id"))
        batch_op.drop_index(batch_op.f("ix_technology_evidence_published_at"))
        batch_op.drop_index(batch_op.f("ix_technology_evidence_organization_id"))
        batch_op.drop_index(batch_op.f("ix_technology_evidence_is_demo"))
        batch_op.drop_index(batch_op.f("ix_technology_evidence_content_hash"))
        batch_op.drop_index("ix_evidence_technology_date")

    op.drop_table("technology_evidence")
    with op.batch_alter_table("technology_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technology_assessments_technology_id"))

    op.drop_table("technology_assessments")
    op.drop_table("startups")
    with op.batch_alter_table("staged_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_staged_evidence_run_id"))

    op.drop_table("staged_evidence")
    with op.batch_alter_table("pipeline_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_steps_run_id"))

    op.drop_table("pipeline_steps")
    op.drop_table("institutions")
    op.drop_table("briefings")
    with op.batch_alter_table("technology_scores", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technology_scores_technology_id"))

    op.drop_table("technology_scores")
    with op.batch_alter_table("technology_keywords", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technology_keywords_technology_id"))

    op.drop_table("technology_keywords")
    op.drop_table("reports")
    with op.batch_alter_table("radar_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_radar_history_technology_id"))

    op.drop_table("radar_history")
    op.drop_table("pipeline_runs")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_technology_id"))
        batch_op.drop_index(batch_op.f("ix_organizations_kind"))

    op.drop_table("organizations")
    with op.batch_alter_table("detected_signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detected_signals_technology_id"))

    op.drop_table("detected_signals")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_analyses_technology_id"))

    op.drop_table("ai_analyses")
    op.drop_table("users")
    with op.batch_alter_table("technologies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_technologies_domain"))

    op.drop_table("technologies")
    op.drop_table("technology_domains")
    op.drop_table("system_settings")
    op.drop_table("roles")
    op.drop_table("radar_horizons")
    op.drop_table("ingestion_jobs")
    op.drop_table("authors")
    # ### end Alembic commands ###
