"""Microsoft Entra identities and one time SSO exchanges"""

from alembic import op
import sqlalchemy as sa

revision = "610f7e504cfb"
down_revision = "06f6d5ea49e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sso_exchanges",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("code_hash"),
    )
    with op.batch_alter_table("sso_exchanges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sso_exchanges_expires_at"), ["expires_at"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_subject", sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint("uq_users_external_subject", ["external_subject"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_external_subject", type_="unique")
        batch_op.drop_column("external_subject")

    with op.batch_alter_table("sso_exchanges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sso_exchanges_expires_at"))

    op.drop_table("sso_exchanges")
    # ### end Alembic commands ###
